config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  authenticate :user do
    root "posts#index", as: :authenticated_root
  end

  unauthenticated do
    root "devise/sessions#new", as: :unauthenticated_root
  end

  resources :users, only: [:index, :show] do
    member do
      post :follow
      delete :unfollow
      post :accept_follow
      delete :reject_follow
    end
  end

  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  resources :comments, only: [:create, :destroy] do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

end

app/views/layouts/_sidebar.html.erb
<div class="sidebar-header">
  <h2><i class="fa-solid fa-train"></i> Rails Social</h2>
</div>
<ul class="sidebar-menu main-links">
  <li><%= link_to posts_path, class: "sidebar-link" do %>
    <i class="fa-solid fa-house"></i>
    <span>Home</span>
  <% end %></li>

  <li><%= link_to users_path, class: "sidebar-link" do %>
    <i class="fa-solid fa-users"></i>
    <span>Discover</span>
  <% end %></li>

  <li><%= link_to user_path(current_user), class: "sidebar-link" do %>
    <%= profile_image_for(current_user, size: 30) %>
    <span>Profile</span>
  <% end %></li>

  <li><%= link_to new_post_path(current_user), class: "sidebar-link" do %>
    <i class="fa-solid fa-pen"></i>
    <span>Create Post</span>
  <% end %></li>
</ul>

<ul class="sidebar-menu bottom-links">
  <% if user_signed_in? %>
    <li><%= button_to "Sign Out", destroy_user_session_path, method: :delete, data: { turbo_confirm: "Are you sure you want to sign out?" }, class: "sidebar-link signout" %></li>
  <% else %>
    <li><%= link_to "Log In", new_user_session_path, class: "sidebar-link" %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Social App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="app-container">
      <aside class="sidebar">
        <%= render "layouts/sidebar" %>
      </aside>
    
      <div class="main-content">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Social App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>